version: '3.8'
services:
  sql-compiler:
    build: .
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always